# Generated by Django 3.1.14 on 2022-02-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='mark12_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark12_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
