# Generated by Django 3.1.14 on 2022-02-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='lateral',
            field=models.CharField(choices=[('YES', 'NO'), ('YES', 'YES')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
