# Generated by Django 3.1.14 on 2022-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='mark_graduation',
            field=models.FileField(blank=True, upload_to='d/8'),
        ),
    ]
