# Generated by Django 3.1.14 on 2022-02-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220201_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='mark10_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark10_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark_graduation_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark_graduation_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
