# Generated by Django 3.1.14 on 2022-02-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220209_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='Adhaar',
            field=models.FileField(blank=True, null=True, upload_to='d/2'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='Adhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='caste',
            field=models.FileField(blank=True, null=True, upload_to='d/3'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='charactor_certificate',
            field=models.FileField(blank=True, null=True, upload_to='d/5'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='department',
            field=models.CharField(blank=True, choices=[('MBA department', 'MBA department'), ('Computer Science department', ' Computer Science department'), ('Electrical department', 'Electrical department'), ('Mechanical Department', 'Mechanical Department'), ('Civil Department', 'Civil Department'), ('Electronics and Engineering Department', 'Electronics and Engineering Department')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='fathers_occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='income',
            field=models.FileField(blank=True, null=True, upload_to='d/4'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark10',
            field=models.FileField(blank=True, null=True, upload_to='d/6'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark10_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark10_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark12',
            field=models.FileField(blank=True, null=True, upload_to='d/7'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark12_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark12_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark_diploma',
            field=models.FileField(blank=True, null=True, upload_to='d/7'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark_diploma_obtain',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark_diploma_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark_graduation',
            field=models.FileField(blank=True, null=True, upload_to='d/8'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark_graduation_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mark_graduation_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mobile2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mothers_occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='pan',
            field=models.FileField(blank=True, null=True, upload_to='d/3'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='d/1'),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='d/8'),
        ),
    ]
