# Generated by Django 3.1.14 on 2022-02-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220209_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='session1',
            new_name='session_end',
        ),
        migrations.RenameField(
            model_name='student_data',
            old_name='session2',
            new_name='session_start',
        ),
    ]
