# Generated by Django 3.1.14 on 2022-02-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220201_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='Adhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='mobile2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
