# Generated by Django 3.1.14 on 2022-02-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220209_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='lateral',
            field=models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], max_length=50),
        ),
    ]
